import {useCallback,useEffect,useState} from 'react';
import {IonIcon,IonPage} from '@ionic/react';
import {busOutline,checkmarkCircleOutline,peopleOutline,refreshOutline,timeOutline} from 'ionicons/icons';
import {useHistory} from 'react-router-dom';
import './CrewOperationsPage.css';

const API=import.meta.env.VITE_OPERATOR_API_URL||'http://localhost:4000/api';
type Trip={id:string;service_number:string;departure_at:string;arrival_at:string;status:string;bus_name:string;source_city:string;destination_city:string;passenger_count:number;boarded_count:number;no_show_count:number};

export default function CrewOperationsPage(){
  const history=useHistory();const token=localStorage.getItem('operator_access_token');
  const [trips,setTrips]=useState<Trip[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{setLoading(true);setError('');const response=await fetch(`${API}/operations/assigned-trips`,{headers:{Authorization:`Bearer ${token}`}});const body=await response.json();if(!response.ok||body.success===false)throw new Error(body.message);setTrips(body.data||[])}catch(e){setError(e instanceof Error?e.message:'Unable to load crew trips.')}finally{setLoading(false)}},[token]);
  useEffect(()=>{void load()},[load]);
  const transition=async(trip:Trip,status:string)=>{try{setError('');const response=await fetch(`${API}/operations/trips/${trip.id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status})});const body=await response.json();if(!response.ok||body.success===false)throw new Error(body.message);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update trip.')}};
  const next=(status:string)=>status==='SCHEDULED'?['BOARDING','Start boarding']:status==='BOARDING'?['DEPARTED','Depart bus']:status==='DEPARTED'?['COMPLETED','Complete trip']:null;
  return <IonPage><main className="crew-console"><header><div><small>DRIVER & CONDUCTOR</small><h1>Today’s trip console</h1><p>Start trips, verify boarding, handle no-shows and complete service.</p></div><button onClick={()=>void load()}><IonIcon icon={refreshOutline}/>Refresh</button></header>{error&&<div className="crew-error">{error}</div>}{loading?<div className="crew-empty">Loading assigned trips…</div>:trips.length===0?<div className="crew-empty"><IonIcon icon={checkmarkCircleOutline}/><h2>No active trips</h2><p>Your assigned operational trips will appear here.</p></div>:<section className="crew-trip-list">{trips.map(trip=>{const action=next(trip.status);const boarded=Math.max(0,Number(trip.boarded_count));const total=Math.max(0,Number(trip.passenger_count));return <article className="crew-trip" key={trip.id}><div className="crew-trip-top"><span><IonIcon icon={busOutline}/></span><div><small>{trip.service_number} · {trip.bus_name}</small><h2>{trip.source_city} → {trip.destination_city}</h2></div><b className={trip.status.toLowerCase()}>{trip.status}</b></div><div className="crew-time"><IonIcon icon={timeOutline}/><strong>{new Date(trip.departure_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</strong><span>to</span><strong>{new Date(trip.arrival_at).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'})}</strong></div><div className="crew-manifest"><IonIcon icon={peopleOutline}/><div><strong>{boarded}/{total} boarded</strong><span>{trip.no_show_count} no-show</span></div><progress max={Math.max(1,total)} value={boarded}/></div><div className="crew-actions"><button onClick={()=>history.push('/operator/bookings')}>Passenger manifest</button>{action&&<button className="primary" onClick={()=>void transition(trip,action[0])}>{action[1]}</button>}</div></article>})}</section>}</main></IonPage>;
}
