import { useEffect, useMemo, useState } from 'react';
import { IonIcon, IonPage } from '@ionic/react';
import { addOutline, cashOutline, refreshOutline, saveOutline, shieldCheckmarkOutline, swapHorizontalOutline, timeOutline, trashOutline } from 'ionicons/icons';
import OperatorSidebar from '../../components/operator/OperatorSidebar';
import './OperatorDashboardPage.css';
import './OperatorPoliciesPage.css';

const API=(import.meta.env.VITE_API_BASE_URL||'http://localhost:4600').replace(/\/$/,'');
const token=()=>localStorage.getItem('operator_access_token')||'';
function operator(){try{return JSON.parse(localStorage.getItem('operator')||'{}')}catch{return {}}}
type Rule={hoursBefore:number;refundPercent:number};
type Policy={operator_id:string;rules:Rule[];reschedule_enabled:boolean;reschedule_cutoff_hours:number|string;reschedule_fee:number|string};

const defaults:Rule[]=[{hoursBefore:24,refundPercent:90},{hoursBefore:12,refundPercent:75},{hoursBefore:6,refundPercent:50},{hoursBefore:2,refundPercent:25},{hoursBefore:0,refundPercent:0}];

export default function OperatorPoliciesPage(){
  const op=operator(); const operatorId=op.id||op.operatorId;
  const[policy,setPolicy]=useState<Policy>({operator_id:operatorId,rules:defaults,reschedule_enabled:true,reschedule_cutoff_hours:4,reschedule_fee:0});
  const[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const sorted=useMemo(()=>[...policy.rules].sort((a,b)=>Number(b.hoursBefore)-Number(a.hoursBefore)),[policy.rules]);
  async function load(){if(!operatorId)return;try{setBusy(true);setMessage('');const r=await fetch(`${API}/operators/${operatorId}/cancellation-policy`,{headers:{Authorization:`Bearer ${token()}`}});const b=await r.json();if(!r.ok||b.success===false)throw new Error(b.message||'Unable to load policy');setPolicy({...b.data,rules:Array.isArray(b.data.rules)?b.data.rules:defaults})}catch(e){setMessage(e instanceof Error?e.message:'Unable to load policy')}finally{setBusy(false)}}
  useEffect(()=>{void load()},[operatorId]);
  function updateRule(index:number,key:keyof Rule,value:number){setPolicy(p=>({...p,rules:p.rules.map((r,i)=>i===index?{...r,[key]:value}:r)}))}
  function addRule(){setPolicy(p=>({...p,rules:[...p.rules,{hoursBefore:1,refundPercent:0}]}))}
  function removeRule(index:number){setPolicy(p=>({...p,rules:p.rules.filter((_,i)=>i!==index)}))}
  async function save(){try{setBusy(true);setMessage('');const r=await fetch(`${API}/operators/${operatorId}/cancellation-policy`,{method:'PUT',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`},body:JSON.stringify({rules:policy.rules,rescheduleEnabled:policy.reschedule_enabled,rescheduleCutoffHours:Number(policy.reschedule_cutoff_hours),rescheduleFee:Number(policy.reschedule_fee)})});const b=await r.json();if(!r.ok||b.success===false)throw new Error(b.message||'Unable to save policy');setPolicy(b.data);setMessage('Cancellation & reschedule policy saved successfully.')}catch(e){setMessage(e instanceof Error?e.message:'Unable to save policy')}finally{setBusy(false)}}
  return <IonPage><div className="operator-dashboard-shell"><OperatorSidebar/><main className="policy-page"><header className="policy-header"><div><p>BOOKING RULES</p><h1>Cancellation & Reschedule Policy</h1><span>Control customer refunds, cancellation windows and rescheduling rules for your services.</span></div><div className="policy-head-actions"><button onClick={()=>void load()} disabled={busy}><IonIcon icon={refreshOutline}/>Refresh</button><button className="primary" onClick={()=>void save()} disabled={busy}><IonIcon icon={saveOutline}/>{busy?'Saving…':'Save policy'}</button></div></header>{message&&<div className="policy-message">{message}</div>}
  <section className="policy-summary"><article><IonIcon icon={shieldCheckmarkOutline}/><div><span>Policy rules</span><strong>{policy.rules.length}</strong><small>Refund windows configured</small></div></article><article><IonIcon icon={swapHorizontalOutline}/><div><span>Rescheduling</span><strong>{policy.reschedule_enabled?'Enabled':'Disabled'}</strong><small>{policy.reschedule_cutoff_hours}h cutoff</small></div></article><article><IonIcon icon={cashOutline}/><div><span>Reschedule fee</span><strong>₹{Number(policy.reschedule_fee||0).toFixed(0)}</strong><small>Added to replacement fare</small></div></article></section>
  <section className="policy-grid"><article className="policy-card"><div className="policy-card-head"><div><h2>Cancellation refund windows</h2><p>The first matching window is used when the customer requests cancellation.</p></div><button onClick={addRule}><IonIcon icon={addOutline}/>Add rule</button></div><div className="policy-rules">{sorted.map((rule)=>{const originalIndex=policy.rules.indexOf(rule);return <div className="policy-rule" key={`${rule.hoursBefore}-${originalIndex}`}><div className="policy-rule-icon"><IonIcon icon={timeOutline}/></div><label>Hours before departure<input type="number" min="0" step="1" value={rule.hoursBefore} onChange={e=>updateRule(originalIndex,'hoursBefore',Number(e.target.value))}/></label><div className="policy-arrow">→</div><label>Customer refund %<div className="percent-field"><input type="number" min="0" max="100" value={rule.refundPercent} onChange={e=>updateRule(originalIndex,'refundPercent',Number(e.target.value))}/><span>%</span></div></label><div className="policy-fee"><span>Cancellation fee</span><strong>{100-Number(rule.refundPercent||0)}%</strong></div><button className="policy-delete" disabled={policy.rules.length<=1||rule.hoursBefore===0} onClick={()=>removeRule(originalIndex)}><IonIcon icon={trashOutline}/></button></div>})}</div><div className="policy-example"><strong>Example</strong><span>For a ₹1,000 ticket cancelled 24+ hours before departure, a 90% refund returns ₹900 and keeps ₹100 as the cancellation fee.</span></div></article>
  <aside className="policy-card policy-reschedule"><div className="policy-card-head"><div><h2>Rescheduling</h2><p>Allow customers to move a confirmed booking to another eligible service.</p></div></div><label className="policy-toggle"><div><strong>Allow rescheduling</strong><span>Customer can choose another trip on the same route and operator.</span></div><input type="checkbox" checked={policy.reschedule_enabled} onChange={e=>setPolicy({...policy,reschedule_enabled:e.target.checked})}/><i/></label><label>Close rescheduling before departure<div className="policy-input-suffix"><input type="number" min="0" step="0.5" value={policy.reschedule_cutoff_hours} disabled={!policy.reschedule_enabled} onChange={e=>setPolicy({...policy,reschedule_cutoff_hours:e.target.value})}/><span>hours</span></div></label><label>Reschedule fee<div className="policy-input-prefix"><span>₹</span><input type="number" min="0" step="1" value={policy.reschedule_fee} disabled={!policy.reschedule_enabled} onChange={e=>setPolicy({...policy,reschedule_fee:e.target.value})}/></div></label><div className="policy-note"><IonIcon icon={shieldCheckmarkOutline}/><p><strong>Fare difference protection</strong> If the new trip costs more, the customer pays the difference. If it costs less, the difference is refunded through the payment provider.</p></div></aside></section></main></div></IonPage>;
}
