BEGIN;
-- notification_channel is defined by the platform baseline and shared here.
CREATE TYPE notification_delivery_status AS ENUM ('QUEUED','SENDING','SENT','DELIVERED','FAILED','SUPPRESSED','DEAD_LETTER');
CREATE TABLE notification_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), template_key TEXT NOT NULL UNIQUE, channel notification_channel NOT NULL, category TEXT NOT NULL, legally_required BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE notification_template_versions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), template_id UUID NOT NULL REFERENCES notification_templates(id) ON DELETE CASCADE, version INTEGER NOT NULL, locale TEXT NOT NULL, subject_template TEXT, body_template TEXT NOT NULL, provider_template_id TEXT, status TEXT NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','ACTIVE','ARCHIVED')), created_by UUID REFERENCES identity_users(id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(template_id,version,locale));
CREATE TABLE notification_preferences (user_id UUID NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE, channel notification_channel NOT NULL, category TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE, quiet_hours JSONB, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), PRIMARY KEY(user_id,channel,category));
CREATE TABLE notification_consents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE, channel notification_channel NOT NULL, purpose TEXT NOT NULL, consented_at TIMESTAMPTZ, withdrawn_at TIMESTAMPTZ, evidence JSONB NOT NULL DEFAULT '{}'::JSONB, UNIQUE(user_id,channel,purpose));
CREATE TABLE notification_device_tokens (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID NOT NULL REFERENCES identity_users(id) ON DELETE CASCADE, platform TEXT NOT NULL, token_hash TEXT NOT NULL UNIQUE, token_encrypted TEXT NOT NULL, last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), expires_at TIMESTAMPTZ, revoked_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE notification_suppressions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), channel notification_channel NOT NULL, recipient_hash TEXT NOT NULL, reason TEXT NOT NULL, expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(channel,recipient_hash));
CREATE TABLE notifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), idempotency_key UUID NOT NULL UNIQUE, template_version_id UUID REFERENCES notification_template_versions(id), event_id UUID UNIQUE, category TEXT NOT NULL, priority TEXT NOT NULL DEFAULT 'NORMAL', payload JSONB NOT NULL, scheduled_for TIMESTAMPTZ NOT NULL DEFAULT NOW(), status notification_delivery_status NOT NULL DEFAULT 'QUEUED', created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ);
CREATE TABLE notification_recipients (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), notification_id UUID NOT NULL REFERENCES notifications(id) ON DELETE CASCADE, user_id UUID REFERENCES identity_users(id), channel notification_channel NOT NULL, recipient_hash TEXT NOT NULL, locale TEXT NOT NULL DEFAULT 'en', status notification_delivery_status NOT NULL DEFAULT 'QUEUED', UNIQUE(notification_id,recipient_hash,channel));
CREATE TABLE notification_delivery_attempts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), recipient_id UUID NOT NULL REFERENCES notification_recipients(id) ON DELETE CASCADE, attempt_number INTEGER NOT NULL, provider_name TEXT NOT NULL, status notification_delivery_status NOT NULL, next_attempt_at TIMESTAMPTZ, error_code TEXT, error_message TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(recipient_id,attempt_number));
CREATE TABLE notification_provider_responses (id BIGSERIAL PRIMARY KEY, attempt_id UUID NOT NULL REFERENCES notification_delivery_attempts(id) ON DELETE CASCADE, provider_message_id TEXT, response_status INTEGER, response_body_redacted JSONB, received_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE notification_inbox (event_id UUID PRIMARY KEY, event_type TEXT NOT NULL, processed_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX notification_dispatch_idx ON notifications(scheduled_for) WHERE status='QUEUED';
CREATE INDEX notification_retry_idx ON notification_delivery_attempts(next_attempt_at) WHERE status IN ('FAILED','SENDING');
CREATE INDEX notification_history_idx ON notification_recipients(user_id, status);
COMMIT;
