BEGIN;

ALTER TABLE buses ADD COLUMN IF NOT EXISTS fuel_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS ownership_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS ac_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS seating_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS seat_layout TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS bus_category TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS axle_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS transmission_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS suspension_type TEXT;
ALTER TABLE buses ADD COLUMN IF NOT EXISTS service_type TEXT;

ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS berth_level TEXT;
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS side TEXT;
ALTER TABLE bus_seats ADD COLUMN IF NOT EXISTS is_accessible BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE bus_compliance ADD COLUMN IF NOT EXISTS permit_type TEXT;
ALTER TABLE bus_compliance ADD COLUMN IF NOT EXISTS chassis_number TEXT;
ALTER TABLE bus_compliance ADD COLUMN IF NOT EXISTS engine_number TEXT;

COMMIT;
