import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Pressable, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Screen } from '@/components/Screen';
import { Card, Muted, Pill, PrimaryButton, SectionTitle, Title } from '@/components/UI';
import { bookingApi } from '@/lib/api';
import { Seat, Stop } from '@/types/api';
import { colors } from '@/theme/colors';

export default function TripSeats(){
  const{id}=useLocalSearchParams<{id:string}>(); const {width}=useWindowDimensions();
  const[busy,setBusy]=useState(true); const[seats,setSeats]=useState<Seat[]>([]); const[boarding,setBoarding]=useState<Stop[]>([]); const[dropping,setDropping]=useState<Stop[]>([]); const[selected,setSelected]=useState<string[]>([]);
  useEffect(()=>{(async()=>{try{const d=await bookingApi.seats(id);setSeats(d.seats||[]);setBoarding(d.boardingPoints||[]);setDropping(d.droppingPoints||[])}catch(e:any){Alert.alert('Unable to load seats',e.message)}finally{setBusy(false)}})()},[id]);
  const selectedSeats=useMemo(()=>seats.filter(s=>selected.includes(s.id)),[seats,selected]);
  const toggle=(seat:Seat)=>{if(seat.status!=='AVAILABLE')return;setSelected(current=>current.includes(seat.id)?current.filter(x=>x!==seat.id):current.length>=6?(Alert.alert('Maximum 6 seats','You can book up to 6 seats in one booking.'),current):[...current,seat.id])};
  const next=()=>{if(!selected.length)return Alert.alert('Select at least one seat');router.push({pathname:'/booking/checkout',params:{tripId:id,seatIds:selected.join(','),seatNumbers:selectedSeats.map(s=>s.seat_number).join(','),boarding:JSON.stringify(boarding),dropping:JSON.stringify(dropping)}})};
  const seatWidth=width<390?'29.5%':width<600?'22%':'15%';
  const total=selectedSeats.reduce((sum,s)=>sum+Number(s.fare||0),0);
  return <Screen>{busy?<ActivityIndicator color={colors.primary}/>:<>
    <View style={s.heading}><View><Title>Select your seats</Title><Muted>Choose up to 6 seats. Availability is rechecked at checkout.</Muted></View><Pill text={`${seats.filter(x=>x.status==='AVAILABLE').length} available`} tone="success"/></View>
    <Card><View style={s.driver}><Text style={s.driverText}>FRONT</Text><View style={s.wheel}><Text>◉</Text></View></View><View style={s.legend}><View style={s.legendItem}><View style={[s.dot,{backgroundColor:colors.successSoft,borderColor:'#86EFAC'}]}/><Text style={s.legendText}>Available</Text></View><View style={s.legendItem}><View style={[s.dot,{backgroundColor:colors.dangerSoft,borderColor:'#FCA5A5'}]}/><Text style={s.legendText}>Booked</Text></View><View style={s.legendItem}><View style={[s.dot,{backgroundColor:colors.primary,borderColor:colors.primary}]}/><Text style={s.legendText}>Selected</Text></View></View>
      <View style={s.grid}>{seats.map(seat=>{const active=selected.includes(seat.id);const available=seat.status==='AVAILABLE';return <Pressable accessibilityRole="button" accessibilityLabel={`Seat ${seat.seat_number}, ${seat.status}, ₹${Number(seat.fare||0)}`} accessibilityState={{selected:active,disabled:!available}} key={seat.id} disabled={!available} onPress={()=>toggle(seat)} style={[s.seat,{width:seatWidth},!available&&s.unavailable,active&&s.selected]}><Text style={[s.seatNo,active&&s.activeText]}>{seat.seat_number}</Text><Text style={[s.price,active&&s.activeText]}>₹{Number(seat.fare||0)}</Text></Pressable>})}</View>
    </Card>
    <Card><SectionTitle>Booking summary</SectionTitle><View style={s.summaryLine}><Text style={s.summaryLabel}>Selected seats</Text><Text style={s.summaryValue}>{selectedSeats.map(x=>x.seat_number).join(', ')||'None'}</Text></View><View style={s.summaryLine}><Text style={s.summaryLabel}>Seat fare</Text><Text style={s.total}>₹{total.toLocaleString('en-IN')}</Text></View><PrimaryButton title={selected.length?`Continue with ${selected.length} seat${selected.length>1?'s':''}`:'Select seats to continue'} onPress={next} disabled={!selected.length}/></Card>
  </>}</Screen>
}
const s=StyleSheet.create({heading:{gap:10},driver:{height:44,borderRadius:12,backgroundColor:colors.surfaceMuted,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:14},driverText:{fontSize:11,fontWeight:'900',letterSpacing:1,color:colors.subtle},wheel:{width:28,height:28,borderRadius:14,borderWidth:2,borderColor:colors.borderStrong,alignItems:'center',justifyContent:'center'},legend:{flexDirection:'row',flexWrap:'wrap',gap:14},legendItem:{flexDirection:'row',alignItems:'center',gap:6},legendText:{fontSize:12,fontWeight:'700',color:colors.muted},dot:{width:16,height:16,borderRadius:5,borderWidth:1},grid:{flexDirection:'row',flexWrap:'wrap',gap:9,justifyContent:'flex-start'},seat:{minWidth:64,maxWidth:90,minHeight:58,borderWidth:1,borderColor:'#86EFAC',backgroundColor:colors.successSoft,borderRadius:12,paddingVertical:8,paddingHorizontal:5,alignItems:'center',justifyContent:'center'},unavailable:{backgroundColor:colors.dangerSoft,borderColor:'#FCA5A5',opacity:.48},selected:{backgroundColor:colors.primary,borderColor:colors.primary,shadowColor:colors.primary,shadowOpacity:.18,shadowRadius:5,elevation:2},seatNo:{fontWeight:'900',color:colors.text,fontSize:14},price:{fontSize:11,color:colors.muted,marginTop:2},activeText:{color:'#fff'},summaryLine:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:16},summaryLabel:{color:colors.muted,fontWeight:'700'},summaryValue:{fontWeight:'900',color:colors.text,flexShrink:1,textAlign:'right'},total:{fontSize:24,fontWeight:'900',color:colors.primary}})
