const express=require('express');
const controller=require('../controllers/booking.controller');
const { requireAuth,optionalAuth }=require('../middlewares/auth.middleware');
const router=express.Router();
const requireInternal=require('../middlewares/internal.middleware');
router.get('/trips/search',controller.searchTrips);
router.get('/trips/:tripId/seats',controller.seatMap);
router.get('/offers',controller.listOffers);
router.post('/coupons/validate',controller.validateCoupon);
router.post('/pricing/quote',controller.pricingQuote);
router.get('/whatsapp/internal/customer',requireInternal,controller.whatsappCustomerBookings);
router.get('/whatsapp/internal/:id/cancellation-quote',requireInternal,controller.whatsappCancellationQuote);
router.post('/whatsapp/internal/:id/cancel',requireInternal,controller.whatsappCancelBooking);
router.post('/whatsapp/internal/:id/support',requireInternal,controller.whatsappSupport);
router.get('/whatsapp/checkout/:token',controller.whatsappCheckoutDetails);
router.post('/whatsapp/checkout/:token/order',controller.whatsappCheckoutOrder);
router.post('/whatsapp/checkout/:token/verify',controller.whatsappCheckoutVerify);
router.post('/whatsapp/checkout/:token/demo-complete',controller.whatsappCheckoutDemoComplete);
router.get('/support/tickets',requireAuth,controller.listSupportTickets);
router.get('/:id/refund-status',requireAuth,controller.refundStatus);
router.post('/:id/support',requireAuth,controller.createSupportTicket);
router.get('/:id/cancellation-quote',requireAuth,controller.cancellationQuote);
router.post('/:id/review',requireAuth,controller.submitReview);
router.get('/:id/reschedule/options',requireAuth,controller.rescheduleOptions);
router.post('/:id/reschedule/quote',requireAuth,controller.rescheduleQuote);
router.post('/:id/reschedule/confirm',requireAuth,controller.confirmReschedule);
router.post('/',optionalAuth,controller.createBooking);
router.get('/customer',requireAuth,controller.customerBookings);
router.post('/:id/payment/order',requireAuth,controller.createPaymentOrder);
router.post('/:id/payment/verify',requireAuth,controller.verifyPayment);
router.post('/:id/payment/complete',controller.completePayment); // backwards-compatible DEMO endpoint
router.get('/:id/ticket',requireAuth,controller.ticket);
router.get('/:id/boarding-pass',requireAuth,controller.boardingPass);
router.patch('/:id/cancel',requireAuth,controller.cancelBooking);
module.exports=router;
