const router = require('express').Router()
const controller = require('../controllers/admin.controller')
const { requireAuth, requireRoles } = require('../middlewares/auth.middleware')

router.use(requireAuth, requireRoles('SUPER_ADMIN'))
router.get('/buses', controller.listBuses)
router.get('/trips', controller.listTrips)
router.get('/bookings', controller.listBookings)
router.get('/payments', controller.listPayments)
router.get('/reconciliation', controller.listPaymentReconciliation)
router.post('/reconciliation/:kind/:id/resolve', controller.resolvePaymentReconciliation)
router.get('/live-trips', controller.listLiveTrips)
router.get('/settlements', controller.listSettlements)
router.post('/settlements', controller.generateSettlement)
router.patch('/settlements/:id/approve', controller.approveSettlement)
router.patch('/settlements/:id/process', controller.processSettlement)
router.patch('/settlements/:id/pay', controller.markSettlementPaid)
router.patch('/settlements/:id/fail', controller.markSettlementFailed)
router.patch('/settlements/:id/retry', controller.retrySettlement)
router.get('/support', controller.listSupportIssues)
router.get('/support/tickets', controller.listSupportTickets)
router.patch('/support/tickets/:id', controller.updateSupportTicket)
router.patch('/trips/:id/cancel', controller.cancelTrip)
router.get('/audit-logs', controller.listAuditLogs)
router.get('/reports/overview', controller.getReportsOverview)
router.get('/promotions', controller.listPromotions)
router.post('/promotions', controller.createPromotion)
router.patch('/promotions/:id/status', controller.updatePromotionStatus)

module.exports = router
