const router = require('express').Router()
const controller = require('../controllers/catalog.controller')
const {requireAuth}=require('../middlewares/auth.middleware')
const {resolveOperator,requirePermission}=require('../middlewares/operator-context.middleware')
router.get('/trips/search/public', controller.searchBookableTrips)
router.use(requireAuth,resolveOperator)
router.post('/routes',requirePermission('catalog.manage'), controller.createRoute)
router.get('/routes',requirePermission('operator.read'), controller.listRoutes)
router.put('/routes/:id/stops',requirePermission('catalog.manage'), controller.updateRouteStops)
router.post('/schedules',requirePermission('trip.manage'),controller.createRecurringSchedule)
router.get('/schedules',requirePermission('operator.read'),controller.listRecurringSchedules)
router.post('/schedules/:id/generate',requirePermission('trip.manage'),controller.materializeSchedule)
router.put('/schedules/:id/exceptions',requirePermission('trip.manage'),controller.upsertScheduleException)
router.post('/trips',requirePermission('trip.manage'), controller.createTrip)
router.get('/trips',requirePermission('operator.read'), controller.listTrips)
router.get('/trips/operator-bookings',requirePermission('booking.read'), controller.operatorBookings)
router.get('/operator-bookings',requirePermission('booking.read'), controller.operatorBookings)
router.get('/trips/:id/fares',requirePermission('operator.read'), controller.getTripFares)
router.put('/trips/:id/fares',requirePermission('trip.manage'), controller.upsertTripFares)
router.get('/trips/:id/inventory',requirePermission('inventory.manage'), controller.getTripInventory)
router.patch('/trips/:id/publish',requirePermission('trip.manage'), controller.publishTrip)
router.get('/trips/:id/operations',requirePermission('operator.read'), controller.getTripOperations)
router.put('/trips/:id/stops',requirePermission('trip.manage'), controller.updateTripStops)
router.patch('/trips/:id/seats/block',requirePermission('inventory.manage'), controller.setSeatBlocks)
router.put('/trips/:id/fare-rules',requirePermission('trip.manage'), controller.upsertFareRules)
router.patch('/trips/:id/cancel',requirePermission('trip.manage'), controller.cancelTrip)
router.post('/operator-bookings/:id/boarding',requirePermission('boarding.manage'), controller.verifyBoarding)
router.get('/operations/assigned-trips',requirePermission('trip.operate'),controller.operationalTrips)
router.patch('/operations/trips/:id/status',requirePermission('trip.operate'),controller.transitionTrip)

module.exports = router
