const router = require('express').Router()
const controller = require('../controllers/catalog.controller')
router.post('/routes', controller.createRoute)
router.get('/routes', controller.listRoutes)
router.put('/routes/:id/stops', controller.updateRouteStops)
router.post('/trips', controller.createTrip)
router.get('/trips', controller.listTrips)
router.get('/trips/operator-bookings', controller.operatorBookings)
router.get('/operator-bookings', controller.operatorBookings)
router.get('/trips/search/public', controller.searchBookableTrips)
router.get('/trips/:id/fares', controller.getTripFares)
router.put('/trips/:id/fares', controller.upsertTripFares)
router.get('/trips/:id/inventory', controller.getTripInventory)
router.patch('/trips/:id/publish', controller.publishTrip)
router.get('/trips/:id/operations', controller.getTripOperations)
router.put('/trips/:id/stops', controller.updateTripStops)
router.patch('/trips/:id/seats/block', controller.setSeatBlocks)
router.put('/trips/:id/fare-rules', controller.upsertFareRules)
router.patch('/trips/:id/cancel', controller.cancelTrip)
router.post('/operator-bookings/:id/boarding', controller.verifyBoarding)

module.exports = router
