import { useEffect,useMemo,useState } from 'react';
import { BadgePercent, CalendarClock, CircleDollarSign, PauseCircle, Plus, RefreshCw, Search, TicketCheck } from 'lucide-react';
import { createPromotion,getPromotions,setPromotionStatus,type AdminPromotion } from './services/admin-operations-api';
import { Badge,Empty,PageHeader,Stat,date,money } from './all-buses-page';
import './admin-operations.css';
import './promotions-page.css';

const initial={code:'',title:'',description:'',discountType:'PERCENTAGE',discountValue:'10',maxDiscountAmount:'',minBookingAmount:'',usageLimit:'',perUserLimit:'1',startsAt:new Date().toISOString().slice(0,10),endsAt:new Date(Date.now()+30*86400000).toISOString().slice(0,10),status:'DRAFT'};
export function PromotionsPage(){const[items,setItems]=useState<AdminPromotion[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[q,setQ]=useState(''),[filter,setFilter]=useState('ALL'),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[form,setForm]=useState(initial);
async function load(){try{setLoading(true);setError('');setItems(await getPromotions())}catch(e){setError(e instanceof Error?e.message:'Unable to load promotions')}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
const rows=useMemo(()=>items.filter(x=>(filter==='ALL'||x.status===filter)&&`${x.code} ${x.title||''} ${x.description||''} ${x.operator_name||''}`.toLowerCase().includes(q.toLowerCase())),[items,q,filter]);
async function save(e:React.FormEvent){e.preventDefault();try{setBusy(true);setError('');await createPromotion({code:form.code,title:form.title,description:form.description,discountType:form.discountType,discountValue:Number(form.discountValue),maxDiscountAmount:form.maxDiscountAmount?Number(form.maxDiscountAmount):null,minBookingAmount:form.minBookingAmount?Number(form.minBookingAmount):undefined,usageLimit:form.usageLimit?Number(form.usageLimit):null,perUserLimit:form.perUserLimit?Number(form.perUserLimit):null,startsAt:new Date(`${form.startsAt}T00:00:00`).toISOString(),endsAt:new Date(`${form.endsAt}T23:59:59`).toISOString(),status:form.status});setShow(false);setForm(initial);await load()}catch(e){setError(e instanceof Error?e.message:'Unable to create promotion')}finally{setBusy(false)}}
async function toggle(x:AdminPromotion){try{setBusy(true);await setPromotionStatus(x.id,x.status==='ACTIVE'?'PAUSED':'ACTIVE');await load()}catch(e){setError(e instanceof Error?e.message:'Unable to update promotion')}finally{setBusy(false)}}
const active=items.filter(x=>x.status==='ACTIVE').length,redemptions=items.reduce((s,x)=>s+Number(x.redemption_count||0),0),saved=items.reduce((s,x)=>s+Number(x.redeemed_amount||0),0);
return <div className="admin-ops-page promotions-page"><PageHeader title="Offers & Coupons" description="Create, schedule and control customer promotions with usage and budget visibility." loading={loading} onRefresh={load}/><div className="promo-create-row"><button className="promo-primary" onClick={()=>setShow(true)}><Plus/>Create promotion</button></div>{error&&<div className="admin-ops-error">{error}</div>}<div className="admin-ops-stats"><Stat icon={<BadgePercent/>} label="Promotions" value={items.length}/><Stat icon={<CalendarClock/>} label="Active now" value={active}/><Stat icon={<TicketCheck/>} label="Redemptions" value={redemptions}/><Stat icon={<CircleDollarSign/>} label="Customer savings" value={money(saved,'INR')}/></div><section className="admin-ops-panel"><div className="admin-ops-toolbar"><div className="admin-ops-search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search code or offer"/></div><div className="admin-ops-filters">{['ALL','ACTIVE','DRAFT','PAUSED','EXPIRED'].map(f=><button key={f} className={`admin-ops-filter ${filter===f?'active':''}`} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="admin-ops-table-wrap"><table className="admin-ops-table"><thead><tr><th>Promotion</th><th>Discount</th><th>Eligibility</th><th>Usage</th><th>Schedule</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong className="promo-code">{x.code}</strong><span className="admin-ops-sub">{x.title||x.description||'BusGo offer'}</span></td><td><strong>{x.discount_type==='PERCENTAGE'?`${Number(x.discount_value)}%`:money(x.discount_value,'INR')}</strong><span className="admin-ops-sub">{x.max_discount_amount?`Max ${money(x.max_discount_amount,'INR')}`:'No max cap'}</span></td><td>{x.operator_name||'All operators'}<span className="admin-ops-sub">{x.eligibility&&'minBookingAmount' in x.eligibility?`Min ${money(Number((x.eligibility as any).minBookingAmount),'INR')}`:'Any booking amount'}</span></td><td><strong>{x.redemption_count}</strong>{x.usage_limit?<span className="admin-ops-sub">of {x.usage_limit}</span>:<span className="admin-ops-sub">Unlimited</span>}</td><td>{date(x.starts_at)}<span className="admin-ops-sub">to {date(x.ends_at)}</span></td><td><Badge value={x.status}/></td><td><button className="promo-action" disabled={busy||x.status==='EXPIRED'} onClick={()=>void toggle(x)}>{x.status==='ACTIVE'?<><PauseCircle/>Pause</>:<><RefreshCw/>Activate</>}</button></td></tr>)}</tbody></table>{!loading&&!rows.length&&<Empty icon={<BadgePercent/>} title="No promotions found" text="Create a coupon or adjust the current filter."/>}</div></section>
{show&&<div className="promo-backdrop" onMouseDown={()=>setShow(false)}><form className="promo-modal" onSubmit={save} onMouseDown={e=>e.stopPropagation()}><div className="promo-modal-head"><div><span>MARKETING</span><h2>Create promotion</h2><p>Discounts are validated again by the backend when a booking is created.</p></div><button type="button" onClick={()=>setShow(false)}>×</button></div><div className="promo-form"><label>Coupon code<input required maxLength={24} value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,'')})} placeholder="BUSGO20"/></label><label>Offer title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Summer travel offer"/></label><label className="wide">Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Save on eligible BusGo bookings."/></label><label>Discount type<select value={form.discountType} onChange={e=>setForm({...form,discountType:e.target.value})}><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed amount</option></select></label><label>Discount value<input required type="number" min="1" max={form.discountType==='PERCENTAGE'?100:100000} value={form.discountValue} onChange={e=>setForm({...form,discountValue:e.target.value})}/></label><label>Maximum discount<input type="number" min="0" value={form.maxDiscountAmount} onChange={e=>setForm({...form,maxDiscountAmount:e.target.value})} placeholder="Optional"/></label><label>Minimum booking<input type="number" min="0" value={form.minBookingAmount} onChange={e=>setForm({...form,minBookingAmount:e.target.value})} placeholder="Optional"/></label><label>Global usage limit<input type="number" min="1" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})} placeholder="Unlimited"/></label><label>Per-user limit<input type="number" min="1" value={form.perUserLimit} onChange={e=>setForm({...form,perUserLimit:e.target.value})}/></label><label>Starts<input required type="date" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})}/></label><label>Ends<input required type="date" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option>DRAFT</option><option>ACTIVE</option></select></label></div><div className="promo-modal-actions"><button type="button" onClick={()=>setShow(false)}>Cancel</button><button className="promo-primary" disabled={busy}>{busy?'Creating…':'Create promotion'}</button></div></form></div>}</div>}
